### ISSUE TITLE
Is it possible to use full openpose file for the humanSD pose?

### ISSUE THREAD

**Issue by p0mad** [IDEA-Research/HumanSD#10]
Hi, I was wondering if it is possible to use face + hands in addition to pose from the openpose in the HumanSD?

Thanks
Best regards

**Comment by juxuan27** [comment]
Hi, @p0mad ! Thank you for your focus.
You need to prepare corresponding training data for full openpose file and retrain the model. Currently, we only support 17 coco keypoints.
