### ISSUE TITLE
How to follow the *.parquet files to download the images

### ISSUE THREAD

**Issue by ucasyjz** [IDEA-Research/HumanSD#11]

**Comment by juxuan27** [comment]
Hi, @yang326922943 ! You may refer to https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion-aesthetic.md to download images with  .parquet files. Noted that the order of Laion-Human is different with that in the link. You may need to make some changes to the code.

**Comment by ucasyjz** [comment]
Thank you! Moreover, we find that the images do not match the poses, can you give me a guidance?

**Comment by juxuan27** [comment]
Our images do not use initial .parquet files in Laion, but use the .parquet files provided in our google drive. You may check the correct .parquet files and it will match the pose annotations in our google drive.

**Comment by juxuan27** [comment]
You can check https://github.com/IDEA-Research/HumanSD/issues/4 for details.

**Comment by zhhezhhe** [comment]
Will you provide a download script?

**Comment by juxuan27** [comment]
Hi, @zhhezhhe . We have provided the download script, please refer to the readme.
