### ISSUE TITLE
After clicking the 'Run' button, the resutls are not obtained and the demo seems running. Can you give me some guidances?

### ISSUE THREAD

**Issue by ucasyjz** [IDEA-Research/HumanSD#12]

**Comment by juxuan27** [comment]
Hi, @yang326922943 ! Thank you for your focus. But can you give some detailed problem description (e.g. program error output)?

**Comment by zhangzhao2022** [comment]
> Hi, @yang326922943 ! Thank you for your focus. But can you give some detailed problem description (e.g. program error output)?

I waited for 10 minutes, the demo is still running, but GPU memory does not change.

**Comment by zhangzhao2022** [comment]
> _No description provided._

Change numpy version to 1.23.1, and disable the proxy. This works for me
