### ISSUE TITLE
Which model ckpt of SD used in the paper for finetune, and how to load the model ckpt of SD in the main.py

### ISSUE THREAD

**Issue by ucasyjz** [IDEA-Research/HumanSD#13]
Can you give me some guidance, thank you

**Comment by juxuan27** [comment]
Hi, @yang326922943 ! Thank you for your focus.
We directly use stable diffusion v2.1's checkpoint and you can directly load the checkpoint using the given code (with the provided yaml file).

**Comment by ucasyjz** [comment]
Thanks, I have another question, how the Quantitative Results are obtained, on which dataset and with which python file

**Comment by juxuan27** [comment]
Please refer to the supplementary file for detail calculation of Quantitative Results. We mainly use torchmetrics and COCOAPI to calculate the metrics. The code will be release as soon as possible.

**Comment by juxuan27** [comment]
Updated at https://github.com/IDEA-Research/HumanSD/tree/main/utils/metrics
