### ISSUE TITLE
About GHI dataset.

### ISSUE THREAD

**Issue by yxsysu** [IDEA-Research/HumanSD#17]
Hi, I am interested in the GHI dataset. I am wondering whether the GHI dataset will be released.
Thank you for your reply.

**Comment by juxuan27** [comment]
Hi, @yxsysu . Sorry, at present we do not plan to release the GHI dataset. But we have provided the scripts of generating GHI dataset [here](https://drive.google.com/drive/folders/1RuSzd1DUuB4HnB0ua-TDNtqonCumi3Ht?usp=sharing). You can also see these scripts after applying for the Laion-Human dataset. The whole generation process may take a few days.
