### ISSUE TITLE
ValueError: 'cuda' is not a valid DistributedType

### ISSUE THREAD

**Issue by Source419** [IDEA-Research/HumanSD#18]
![image](https://github.com/IDEA-Research/HumanSD/assets/61913373/8541e57e-39ac-41e8-9db2-bef9bff6e081)
I tried to train, but I encountered this error, has anyone encountered similar problems?

**Comment by Zavianx** [comment]
Hi, I have met this error too, Can u share your solution

**Comment by liming-ai** [comment]
Hi, @Source419 

Same error here, could you please provide some advice?
