### ISSUE TITLE
pose_ckpt

### ISSUE THREAD

**Issue by baeckgoo** [IDEA-Research/HumanSD#19]
Thank you for your great work!

Here is the file path for pose_ckpt.
https://github.com/IDEA-Research/HumanSD/blob/d8fb179f67824944c9728ab8d55a3616b207b148/configs/humansd/humansd-finetune.yaml#L22

But, I couldn't find 'higherhrnet_w48_coco_512x512_udp.pth' ' in the shared link:
https://drive.google.com/drive/folders/1NLQAlF7i0zjEpd-XY0EcVw9iXP5bB5BJ

Should I change the filename in the config?

**Comment by juxuan27** [comment]
Hi, @baeckgoo ! Sorry for the typo error. I have updated the config file to a new ckpt name: higherhrnet_w48_humanart_512x512_udp.pth
