### ISSUE TITLE
Aesthetics_Human 是你们通过人体检测器从laion-Aesthetics中筛选出来的子集吗？

### ISSUE THREAD

**Issue by SummerTrains** [IDEA-Research/HumanSD#2]
如题

**Comment by juxuan27** [comment]
Hi, @SummerTrains ! Thank you for your focus and sorry for the late reply.

The answer is yes. We use HigherHRNet trained on [HumanArt](https://github.com/IDEA-Research/HumanArt) (a multi-scenario human dataset) to filter the images.
