### ISSUE TITLE
Memory issue when calculating FID

### ISSUE THREAD

**Issue by baeckgoo** [IDEA-Research/HumanSD#20]
Thank you for sharing your great work!

I'd like to calculate FID given source images and generated images.

In your paper, the number of validation images is 3,750 images.
In my experiment, the number of images is 3000, less than your case.
When I calculate FID, out of memory issue happened on V100 gpu in [here](https://github.com/IDEA-Research/HumanSD/blob/d8fb179f67824944c9728ab8d55a3616b207b148/utils/metrics/quality_metrics.py#L47) 

Could you please give me any comments to solve it?

**Comment by juxuan27** [comment]
Hi, @baeckgoo . Thank you for your focus!
I haven't encounter this issue but maybe you can try whether change hyper-parameters such as fid_model_feature will help.
