### ISSUE TITLE
About the data quality

### ISSUE THREAD

**Issue by leesky1c** [IDEA-Research/HumanSD#21]
Hi Xuan,

I used the [utils/download_data.py](https://github.com/IDEA-Research/HumanSD/blob/main/utils/download_data.py) script from the repository to download data via the Laion-Human's URL. 

After downloading 1000 images, I randomly sampled several images which looks like:

![000002238](https://github.com/IDEA-Research/HumanSD/assets/19488095/fc5bf5ea-2abf-4bee-b329-b62c948a05b2)
![000001138](https://github.com/IDEA-Research/HumanSD/assets/19488095/474eb446-0b3a-4bdd-bf4c-d9f0f1b82a48)
![000001038](https://github.com/IDEA-Research/HumanSD/assets/19488095/29097bc6-ae41-4e15-b364-3b26ec6574ee)

I would like to confirm if I missed any steps or where the problem occurred.

Thanks.

**Comment by juxuan27** [comment]
Hi, @leeskyed . Thank you for your focus!
The images are selected with pose estimation score>0 thus containing some images without human. This is to ensure the flexibility of using different pose estimation score in training. You can try using the given score>0.02 in our code as a selection threshold, you will find much less false detection.

**Comment by leesky1c** [comment]
Thanks, I will give it a try!   :)
