### ISSUE TITLE
huggingface connect error

### ISSUE THREAD

**Issue by Kai-0515** [IDEA-Research/HumanSD#22]
hi thx for your excellent work!
when the code automatically downloads the 'open_clip_pytorch_model.bin' model, the hugging face can not connect like this. 
<img width="1209" alt="截屏2023-10-18 下午4 48 26" src="https://github.com/IDEA-Research/HumanSD/assets/57972031/338cf3b4-1fdd-4f0b-890e-77cf5267d23d">
And I also try to upload the .bin file to the code, but where I should upload to. Directly up down the '～./cache/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K' also can not work. 
Looking forward to your reply！

**Comment by juxuan27** [comment]
Hi, @Kai-0515 , maybe you can try adding your personal huggingface token to the downloading code or changing your cluster network.

**Comment by Kai-0515** [comment]
hi where can I add my personal token?

**Comment by juxuan27** [comment]
I think you need to find which line of code through out this error and add your personal token as: pipe = pipeline("xxx", model="xxx", token="your token"). More details can be found [here](https://huggingface.co/docs/hub/security-tokens).
