### ISSUE TITLE
'cuda' is not a valid DistributedType

### ISSUE THREAD

**Issue by Kai-0515** [IDEA-Research/HumanSD#24]
Hi when I train the humansd model, I met the 'cuda' is not a valid DistributedType'
I set the GPU to 1 can not fix.
<img width="1687" alt="截屏2023-10-20 下午4 35 17" src="https://github.com/IDEA-Research/HumanSD/assets/57972031/5b1a541c-dfe6-42b4-9c4f-3968353c7a14">

**Comment by VicZlq** [comment]
> Hi when I train the humansd model, I met the 'cuda' is not a valid DistributedType' I set the GPU to 1 can not fix. <img alt="截屏2023-10-20 下午4 35 17" width="1687" src="https://user-images.githubusercontent.com/57972031/276872537-5b1a541c-dfe6-42b4-9c4f-3968353c7a14.png">

Hello, did you follow up on this issue? I had a similar problem when I reproduced it. I changed the 'cuda' to 'gpu' and the bug was solved, but then opt.train=False and I couldn't get to trainer.fit(model, data), have you encountered this?
