### ISSUE TITLE
How to generate poses for custom images. Please guide.

### ISSUE THREAD

**Issue by hacker009-sudo** [IDEA-Research/HumanSD#25]
@juxuan27 , Can you please explain how to create .npz files for custom dataset.

**Comment by hacker009-sudo** [comment]
@juxuan27 , Actually I need to know how we can prepare our custom dataset. Please guide.

**Comment by juxuan27** [comment]
Hi, to prepare your custom dataset, you need to prepare image-pose annotation-text annotation pairs. Specifically, image path and text annotation can be directly putted in mapping_file.json as our given LAION-Human. As for the pose annotation, we generate it directly with [MMPose](https://github.com/open-mmlab/mmpose) and provide the npz file path in mapping_file.json.

**Comment by xiao2mo** [comment]
please give a toy demo for generate such kind of feature using related ckpt.

**Comment by xiao2mo** [comment]
@juxuan27
