### ISSUE TITLE
laion human dataset download

### ISSUE THREAD

**Issue by Kai-0515** [IDEA-Research/HumanSD#26]
The process can not go on flu/data/disk1/code/HumanSD/humansd_data/datasets/LaionAesthetics/images/00003.parquetently, and even can not download images/00000 wholely, only up to 000095.jpg.
Can u provide a way to directly download the jpg files? I think it is not stable to download from url.
<img width="358" alt="截屏2023-10-22 下午8 00 00" src="https://github.com/IDEA-Research/HumanSD/assets/57972031/e6054d23-5c7f-4668-a5f3-98e781c3451e">

**Comment by juxuan27** [comment]
Hi, @Kai-0515 ! Thank you for your focus.
Would you please provide the download scripts you use? And also, is there any running error or something else that stops the downloading?
