### ISSUE TITLE
How to run the task about (img+pose+text)2img

### ISSUE THREAD

**Issue by Tsai-chia-hsiang** [IDEA-Research/HumanSD#27]
@juxuan27 
Hi, I found that all the demo  sample is either img2img or pose2img.
Could you please demo how to give img and pose as condition and generate a the result? 
thanks!

**Comment by juxuan27** [comment]
Hi, @Tsai-chia-hsiang ! Thank you for your focus.
At present, we only support pose2img. The pose is converted to image using visualization tools.

**Comment by Tsai-chia-hsiang** [comment]
OK, Thanks !
