### ISSUE TITLE
ImportError: cannot import name 'inference_bottom_up_pose_model' from 'mmpose.apis'

### ISSUE THREAD

**Issue by WenB777** [IDEA-Research/HumanSD#5]

**Comment by juxuan27** [comment]
Hi, @WenB777 ! Thank you for your focus. Please make sure you have installed mmpose correctly. [Here](https://mmpose.readthedocs.io/en/v0.28.0/api.html?highlight=inference_bottom_up_pose_model#mmpose.apis.inference_bottom_up_pose_model) is the document of mmpose for your reference.

**Comment by WenB777** [comment]
> 



> 嗨， ！感谢您的关注。请确保您已正确安装mmpose。[这是](https://mmpose.readthedocs.io/en/v0.28.0/api.html?highlight=inference_bottom_up_pose_model#mmpose.apis.inference_bottom_up_pose_model) mmpose 的文档供您参考。

Thank you for reply, I have solve the problem by your answer. The mistake is comes from the wrong version of mmpose.
