### ISSUE TITLE
Train with fp16

### ISSUE THREAD

**Issue by yjhong89** [IDEA-Research/HumanSD#6]
I am trying to fine-tune HumanSD ckpt with `use_fp16=True` option. (I installed xformers) 
But it still RuntimeError occurs like below
![image](https://github.com/Stability-AI/stablediffusion/assets/26890721/d33077fb-b778-4627-86d8-55fbe611ee3c)
- I think there needs some codes converting model weight to fp16 but there isn't any convertion or autocast
- https://github.com/IDEA-Research/HumanSD/blob/fe480f723f80bc62b158503e858c31174fa629c1/ldm/modules/diffusionmodules/openaimodel.py#L23

- Is it possible training stable diffusion with fp16 ??
- If I set `use_fp16=False` in configs, it works

**Comment by juxuan27** [comment]
Hi, @yjhong89 ! Thank you for your focus.
I have tried to train with `use_fp16=True` but it just works fine. Maybe you can try to force the input to FloatTensor in your case? To do so, you can go to comparison_models/ControlNet/ldm/models/diffusion/ddpm.py and find get_input function in your latent diffusion class, then use `.to(your expected data type)`.

**Comment by yjhong89** [comment]
Thanks!

**Comment by xiao2mo** [comment]
你能自己复现下吗。把环境发一下，fp16 训练有问题啊。

**Comment by xiao2mo** [comment]
@yjhong89

**Comment by chaunceywx** [comment]
> Thanks!

Have you successfully trained model with fp16 now?
I encountered the same issue. How should I modify the code to train the model with fp16?

**Comment by chaunceywx** [comment]
> Thanks!

@yjhong89
