### ISSUE TITLE
The problem of the model file download

### ISSUE THREAD

**Issue by sherlhw** [IDEA-Research/HumanSD#9]
When I download the "humansd-v1.ckpt" model, the download always fails because the file is too large. Is there any other download link?

**Comment by juxuan27** [comment]
You may email me and I can send you the link with Baidu Netdisk.

**Comment by sherlhw** [comment]
Thanks，my email is ***@***.***


青池゛旧时光ㄟ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDEA-Research/HumanSD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月12日(星期三) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDEA-Research/HumanSD] The problem of the model file download (Issue #9)





 
You may email me and I can send you the link with Baidu Netdisk.

**Comment by sherlhw** [comment]
Thanks，my email is 294722632@qq.com.
